Repository DaSiHaeBom/DaSiHaeBom-BE, pull requests merged in 2025-08, with the labels that each got.

#4 Feat/#2-2: 국세청 사업자등록정보 상태 조회 구현 & Dto 예외 처리 조건 상수화 및 구현
  build.gradle
  src/main/java/com/project/dasihaebom/domain/auth/converter/AuthConverter.java
  src/main/java/com/project/dasihaebom/domain/auth/entity/CorpAuth.java
  src/main/java/com/project/dasihaebom/domain/auth/entity/WorkerAuth.java
  src/main/java/com/project/dasihaebom/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/project/dasihaebom/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/LoginType.java
  src/main/java/com/project/dasihaebom/domain/user/Role.java
  src/main/java/com/project/dasihaebom/domain/user/corp/controller/CorpController.java
  src/main/java/com/project/dasihaebom/domain/user/corp/converter/CorpConverter.java
  src/main/java/com/project/dasihaebom/domain/user/corp/dto/request/CorpReqDto.java
  src/main/java/com/project/dasihaebom/domain/user/corp/dto/response/CorpResDto.java
  src/main/java/com/project/dasihaebom/domain/user/corp/entity/Corp.java
  src/main/java/com/project/dasihaebom/domain/user/corp/exception/CorpErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/command/CorpCommandService.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/command/CorpCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/worker/controller/WorkerController.java
  src/main/java/com/project/dasihaebom/domain/user/worker/converter/WorkerConverter.java
  src/main/java/com/project/dasihaebom/domain/user/worker/dto/request/WorkerReqDto.java
  src/main/java/com/project/dasihaebom/domain/user/worker/entity/Gender.java
  src/main/java/com/project/dasihaebom/domain/user/worker/entity/Worker.java
  src/main/java/com/project/dasihaebom/domain/user/worker/exception/WorkerErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandService.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/global/client/corpNumber/CorpNumberClient.java
  src/main/java/com/project/dasihaebom/global/client/corpNumber/dto/NtsCorpInfoResDto.java
  src/main/java/com/project/dasihaebom/global/config/WebClientConfig.java
  src/main/java/com/project/dasihaebom/global/constant/valid/MessageConstants.java
  src/main/java/com/project/dasihaebom/global/constant/valid/PatternConstants.java
  src/main/java/com/project/dasihaebom/global/util/UpdateUtils.java
Labels: ✨feature

#7 Feat/#1
  src/main/java/com/project/dasihaebom/domain/introduction/controller/Controller.java
  src/main/java/com/project/dasihaebom/domain/introduction/controller/IntroductionController.java
  src/main/java/com/project/dasihaebom/domain/introduction/converter/Converter.java
  src/main/java/com/project/dasihaebom/domain/introduction/converter/IntroductionConverter.java
  src/main/java/com/project/dasihaebom/domain/introduction/dto/request/AnswerReqDto.java
  src/main/java/com/project/dasihaebom/domain/introduction/dto/request/ReqDto.java
  src/main/java/com/project/dasihaebom/domain/introduction/dto/response/AnswerResDto.java
  src/main/java/com/project/dasihaebom/domain/introduction/dto/response/ResDto.java
  src/main/java/com/project/dasihaebom/domain/introduction/entity/Answer.java
  src/main/java/com/project/dasihaebom/domain/introduction/entity/Question.java
  src/main/java/com/project/dasihaebom/domain/introduction/exception/IntroductionErrorCode.java
  src/main/java/com/project/dasihaebom/domain/introduction/repository/AnswerRepository.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/command/IntroductionCommandService.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/command/IntroductionCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/query/IntroductionQueryService.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/query/IntroductionQueryServiceImpl.java
  src/main/java/com/project/dasihaebom/global/config/DataInitializer.java
Labels: ✨feature

#15 Feat/#3-2 자기소개서 조회 기능 추가
  src/main/java/com/project/dasihaebom/domain/introduction/controller/IntroductionController.java
  src/main/java/com/project/dasihaebom/domain/introduction/exception/IntroductionErrorCode.java
  src/main/java/com/project/dasihaebom/domain/introduction/repository/IntroductionRepository.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/query/IntroductionQueryService.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/query/IntroductionQueryServiceImpl.java
Labels: ✨feature

#24 Refactor/#23: 리팩토링 사소한
  src/main/java/com/project/dasihaebom/domain/auth/controller/AuthController.java
  src/main/java/com/project/dasihaebom/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/project/dasihaebom/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/corp/controller/CorpController.java
  src/main/java/com/project/dasihaebom/domain/user/worker/controller/WorkerController.java
  src/main/java/com/project/dasihaebom/domain/validation/controller/ValidationController.java
  src/main/java/com/project/dasihaebom/domain/validation/service/ValidationService.java
  src/main/java/com/project/dasihaebom/domain/validation/service/ValidationServiceImpl.java
  src/main/java/com/project/dasihaebom/global/security/dto/JwtDto.java
  src/main/java/com/project/dasihaebom/global/security/filter/CustomLoginFilter.java
Labels: ♻️refactor

#28 Feat/#27: 카카오맵 api 연동
  src/main/java/com/project/dasihaebom/domain/location/converter/LocationConverter.java
  src/main/java/com/project/dasihaebom/domain/location/entity/Location.java
  src/main/java/com/project/dasihaebom/domain/location/repository/LocationRepository.java
  src/main/java/com/project/dasihaebom/domain/location/service/LocationService.java
  src/main/java/com/project/dasihaebom/domain/location/service/LocationServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/location/service/command/LocationCommandService.java
  src/main/java/com/project/dasihaebom/domain/location/service/command/LocationCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/location/service/query/LocationQueryService.java
  src/main/java/com/project/dasihaebom/domain/location/service/query/LocationQueryServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/corp/converter/CorpConverter.java
  src/main/java/com/project/dasihaebom/domain/user/corp/entity/Corp.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/command/CorpCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/worker/converter/WorkerConverter.java
  src/main/java/com/project/dasihaebom/domain/user/worker/entity/Worker.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/global/client/exception/ClientErrorCode.java
  src/main/java/com/project/dasihaebom/global/client/exception/ClientException.java
  src/main/java/com/project/dasihaebom/global/client/location/coordinate/CoordinateClient.java
  src/main/java/com/project/dasihaebom/global/client/location/coordinate/dto/KakaoCoordinateInfoResDto.java
  src/main/java/com/project/dasihaebom/global/config/WebClientConfig.java
  src/main/java/com/project/dasihaebom/global/util/CoordinateUtils.java
  src/main/resources/application-prod.yml
Labels: ✨feature

#31 Feat/#2-5: 회원 탈퇴 구현 & 전화번호 중복 인증 예외 처리
  src/main/java/com/project/dasihaebom/domain/user/corp/entity/Corp.java
  src/main/java/com/project/dasihaebom/domain/user/worker/controller/WorkerController.java
  src/main/java/com/project/dasihaebom/domain/user/worker/entity/Worker.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandService.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/validation/exception/ValidationErrorCode.java
  src/main/java/com/project/dasihaebom/domain/validation/service/ValidationServiceImpl.java
Labels: ✨feature

#34 Feat/#9-4: 회원 탈퇴시 쿠키 삭제 & jti로 블랙리스트 보안 강화
  src/main/java/com/project/dasihaebom/domain/user/worker/controller/WorkerController.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandService.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/global/constant/common/CommonConstants.java
  src/main/java/com/project/dasihaebom/global/constant/redis/RedisConstants.java
  src/main/java/com/project/dasihaebom/global/security/controller/SecurityController.java
  src/main/java/com/project/dasihaebom/global/security/filter/CustomLoginFilter.java
  src/main/java/com/project/dasihaebom/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/dasihaebom/global/security/handler/CustomLogoutHandler.java
  src/main/java/com/project/dasihaebom/global/security/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/project/dasihaebom/global/security/service/SecurityService.java
  src/main/java/com/project/dasihaebom/global/security/utils/JwtUtil.java
  src/main/java/com/project/dasihaebom/global/util/CookieUtils.java
Labels: ✨feature

#35 Feat/#2-6: 회원 기능 구현
  src/main/java/com/project/dasihaebom/domain/user/corp/exception/CorpErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/command/CorpCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/worker/controller/WorkerController.java
  src/main/java/com/project/dasihaebom/domain/user/worker/exception/WorkerErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandService.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/validation/controller/ValidationController.java
  src/main/java/com/project/dasihaebom/domain/validation/service/ValidationServiceImpl.java
  src/main/java/com/project/dasihaebom/global/constant/common/CommonConstants.java
  src/main/java/com/project/dasihaebom/global/constant/redis/RedisConstants.java
  src/main/java/com/project/dasihaebom/global/constant/scope/ScopeConstants.java
  src/main/java/com/project/dasihaebom/global/security/controller/SecurityController.java
  src/main/java/com/project/dasihaebom/global/security/filter/CustomLoginFilter.java
  src/main/java/com/project/dasihaebom/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/dasihaebom/global/security/handler/CustomLogoutHandler.java
  src/main/java/com/project/dasihaebom/global/security/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/project/dasihaebom/global/security/service/SecurityService.java
  src/main/java/com/project/dasihaebom/global/security/utils/JwtUtil.java
  src/main/java/com/project/dasihaebom/global/util/CookieUtils.java
  src/main/resources/application-prod.yml
Labels: ✨feature

#36 Develop 배포
  src/main/java/com/project/dasihaebom/domain/user/corp/exception/CorpErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/command/CorpCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/worker/exception/WorkerErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/validation/controller/ValidationController.java
  src/main/java/com/project/dasihaebom/domain/validation/service/ValidationServiceImpl.java
  src/main/java/com/project/dasihaebom/global/constant/scope/ScopeConstants.java
  src/main/resources/application-prod.yml
Labels: 💚ci/cd

#37 ✨feat: worker 연관관계 orphanRemoval 설정
  src/main/java/com/project/dasihaebom/domain/user/worker/entity/Worker.java
Labels: ✨feature

#42 Develop 배포
  build.gradle
  src/main/java/com/project/dasihaebom/domain/introduction/service/command/IntroductionCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/location/entity/Coordinates.java
  src/main/java/com/project/dasihaebom/domain/location/service/LocationServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/resume/controller/ResumeController.java
  src/main/java/com/project/dasihaebom/domain/resume/converter/ResumeConverter.java
  src/main/java/com/project/dasihaebom/domain/resume/dto/request/ResumeSearchCondition.java
  src/main/java/com/project/dasihaebom/domain/resume/dto/response/ResumeResDto.java
  src/main/java/com/project/dasihaebom/domain/resume/entity/Resume.java
  src/main/java/com/project/dasihaebom/domain/resume/exception/ResumeErrorCode.java
  src/main/java/com/project/dasihaebom/domain/resume/repository/ResumeRepository.java
  src/main/java/com/project/dasihaebom/domain/resume/repository/ResumeRepositoryCustom.java
  src/main/java/com/project/dasihaebom/domain/resume/repository/ResumeRepositoryCustomImpl.java
  src/main/java/com/project/dasihaebom/domain/resume/service/command/ResumeCommandService.java
  src/main/java/com/project/dasihaebom/domain/resume/service/command/ResumeCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/resume/service/query/ResumeQueryService.java
  src/main/java/com/project/dasihaebom/domain/resume/service/query/ResumeQueryServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/corp/controller/CorpController.java
  src/main/java/com/project/dasihaebom/domain/user/corp/converter/CorpConverter.java
  src/main/java/com/project/dasihaebom/domain/user/corp/dto/response/CorpResDto.java
  src/main/java/com/project/dasihaebom/domain/user/corp/entity/Corp.java
  src/main/java/com/project/dasihaebom/domain/user/corp/exception/CorpErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/command/CorpCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/query/CorpQueryService.java
  src/main/java/com/project/dasihaebom/domain/user/corp/service/query/CorpQueryServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/worker/controller/WorkerController.java
  src/main/java/com/project/dasihaebom/domain/user/worker/converter/WorkerConverter.java
  src/main/java/com/project/dasihaebom/domain/user/worker/dto/response/WorkerResDto.java
  src/main/java/com/project/dasihaebom/domain/user/worker/entity/Worker.java
  src/main/java/com/project/dasihaebom/domain/user/worker/exception/WorkerErrorCode.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/query/WorkerQueryService.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/query/WorkerQueryServiceImpl.java
  src/main/java/com/project/dasihaebom/global/config/CorsConfig.java
  src/main/java/com/project/dasihaebom/global/config/QuerydslConfig.java
  src/main/java/com/project/dasihaebom/global/config/SecurityConfig.java
  src/main/java/com/project/dasihaebom/global/security/controller/SecurityController.java
Labels: 💚ci/cd

#50 - Refector/fix/#49 기능 통합 및 버그 수정
  build.gradle
  src/main/java/com/project/dasihaebom/domain/introduction/controller/IntroductionController.java
  src/main/java/com/project/dasihaebom/domain/introduction/converter/IntroductionConverter.java
  src/main/java/com/project/dasihaebom/domain/introduction/dto/request/AnswerReqDto.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/command/IntroductionCommandService.java
  src/main/java/com/project/dasihaebom/domain/introduction/service/command/IntroductionCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/license/entity/License.java
  src/main/java/com/project/dasihaebom/domain/license/service/command/LicenseCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/resume/controller/ResumeController.java
  src/main/java/com/project/dasihaebom/domain/resume/converter/ResumeConverter.java
  src/main/java/com/project/dasihaebom/domain/resume/dto/request/ResumeSearchCondition.java
  src/main/java/com/project/dasihaebom/domain/resume/entity/Resume.java
  src/main/java/com/project/dasihaebom/domain/resume/repository/ResumeRepositoryCustomImpl.java
  src/main/java/com/project/dasihaebom/domain/resume/service/command/ResumeCommandServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/resume/service/query/ResumeQueryServiceImpl.java
  src/main/java/com/project/dasihaebom/domain/user/worker/entity/Worker.java
  src/main/java/com/project/dasihaebom/domain/user/worker/service/command/WorkerCommandServiceImpl.java
  src/main/resources/application.yml
Labels: ♻️refactor, 🐛fix
